CREATE SCHEMA IF NOT EXISTS AAB_SCHEMA
CREATE SCHEMA IF NOT EXISTS AAB_SCHEMA_2
CREATE SCHEMA IF NOT EXISTS AAB_SCHEMA_3
CREATE SCHEMA IF NOT EXISTS AAB_SCHEMA_4
CREATE SCHEMA IF NOT EXISTS AAB_SCHEMA_5